package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'ApacheIgniteRelease_Run_ApacheIgnitePostRelease_BuildUploadDockerImages'
in the project with id = 'Releases_ApacheIgniteMain', and delete the patch script.
*/
create(RelativeId("Releases_ApacheIgniteMain"), BuildType({
    id("ApacheIgniteRelease_Run_ApacheIgnitePostRelease_BuildUploadDockerImages")
    name = "-> Run [#2.1] :: Apache Ignite Post Release | Build & Upload Docker Images"
}))

