package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.PowerShellStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.VisualStudioStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.visualStudio
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ignite2_Release_ApacheIgniteMain_ReleaseBuild_PrepareBuildOdbc'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ignite2_Release_ApacheIgniteMain_ReleaseBuild_PrepareBuildOdbc")) {
    expectSteps {
        script {
            name = "Add NuGet executable to PATH"
            enabled = false
            scriptContent = """
                @echo on
                
                echo ##teamcity[setParameter name='env.PATH' value='%%PATH%%;%teamcity.tool.NuGet.CommandLine.DEFAULT%\tools']
            """.trimIndent()
        }
        script {
            name = "Git setup (Ignore chmod settings)"
            workingDir = "%IGNITE_ROOT%"
            scriptContent = "git config core.filemode false"
        }
        maven {
            name = "Change maven version"
            goals = "versions:set"
            pomLocation = """%IGNITE_ROOT%\pom.xml"""
            runnerArgs = """
                -DnewVersion=%IGNITE_VERSION%
                -Pall-java,all-scala,all-other
                -DgenerateBackupPoms=false
                -DgroupId=* -DartifactId=* -DoldVersion=*
                -DprocessDependencies=false
            """.trimIndent()
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
        }
        maven {
            name = "Change dotnet & cpp versions"
            goals = "validate"
            pomLocation = """%IGNITE_ROOT%\pom.xml"""
            runnerArgs = """
                -P update-versions
                -Dnew.ignite.version=%IGNITE_VERSION%
            """.trimIndent()
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
        }
        script {
            name = "Git patch (with changed versions) generation"
            workingDir = "%IGNITE_ROOT%"
            scriptContent = "git diff > ../vote.patch"
        }
        powerShell {
            name = "Build Ignite.NET"
            enabled = false
            platform = PowerShellStep.Platform.x64
            edition = PowerShellStep.Edition.Desktop
            workingDir = "ignite/modules/platforms/dotnet"
            scriptMode = file {
                path = "ignite/modules/platforms/dotnet/build.ps1"
            }
            noProfile = false
            param("jetbrains_powershell_scriptArguments", "-skipJava -skipNuget")
        }
        visualStudio {
            name = "Build 32-bit ODBC binary"
            enabled = false
            path = "ignite/modules/platforms/cpp/project/vs/ignite.sln"
            version = VisualStudioStep.VisualStudioVersion.vs2017
            runPlatform = VisualStudioStep.Platform.x86
            msBuildVersion = VisualStudioStep.MSBuildVersion.V15_0
            msBuildToolsVersion = VisualStudioStep.MSBuildToolsVersion.V15_0
            targets = "odbc:Rebuild"
            configuration = "Release"
            platform = "Win32"
        }
        visualStudio {
            name = "Build 64-bit ODBC binary"
            enabled = false
            executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
            path = "ignite/modules/platforms/cpp/project/vs/ignite.sln"
            version = VisualStudioStep.VisualStudioVersion.vs2017
            runPlatform = VisualStudioStep.Platform.x86
            msBuildVersion = VisualStudioStep.MSBuildVersion.V15_0
            msBuildToolsVersion = VisualStudioStep.MSBuildToolsVersion.V15_0
            targets = "odbc:Rebuild"
            configuration = "Release"
            platform = "x64"
        }
        script {
            name = "Build 32-bit ODBC installer"
            workingDir = """%IGNITE_ROOT%\modules\platforms\cpp"""
            scriptContent = """
                set OPENSSL_ROOT_DIR=%env.OPENSSL_HOME_X86%
                mkdir cmake-build-release-32
                cd cmake-build-release-32
                
                cmake -DWITH_CORE=OFF -DWITH_ODBC=ON -DWITH_ODBC_MSI=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=Win32 -DCMAKE_INSTALL_PREFIX=..\install\x86 ..
                cmake --build . --target install --config Release
            """.trimIndent()
        }
        script {
            name = "Build 64-bit ODBC installer"
            workingDir = """%IGNITE_ROOT%\modules\platforms\cpp"""
            scriptContent = """
                set OPENSSL_ROOT_DIR=%env.OPENSSL_HOME%
                mkdir cmake-build-release-64
                cd cmake-build-release-64
                
                cmake -DWITH_CORE=OFF -DWITH_ODBC=ON -DWITH_ODBC_MSI=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_GENERATOR_PLATFORM=x64 -DCMAKE_INSTALL_PREFIX=..\install\amd64 ..
                cmake --build . --target install --config Release
            """.trimIndent()
        }
        script {
            name = "Build dotnetdoc"
            enabled = false
            workingDir = "ignite/modules/platforms/dotnet/docfx"
            scriptContent = "generate-docs.cmd"
        }
    }
    steps {
        update<MavenBuildStep>(2) {
            name = "[OLD] Change maven version"
            enabled = false
            clearConditions()
        }
        insert(3) {
            script {
                name = "[NEW] Change MAVEN version"
                scriptContent = """
                    set -x
                    
                    sed -r 's|(.*<revision>).*(</revision>)|\1%IGNITE_VERSION%\2|' -i parent/pom.xml
                """.trimIndent()
            }
        }
        update<MavenBuildStep>(4) {
            clearConditions()
        }
        update<ScriptBuildStep>(5) {
            enabled = true
            clearConditions()
        }
        update<PowerShellStep>(6) {
            clearConditions()
        }
        update<VisualStudioStep>(7) {
            clearConditions()
        }
        update<VisualStudioStep>(8) {
            enabled = false
            clearConditions()
        }
        update<ScriptBuildStep>(9) {
            clearConditions()
        }
        update<ScriptBuildStep>(10) {
            enabled = true
            clearConditions()
        }
        update<ScriptBuildStep>(11) {
            enabled = false
            clearConditions()
        }
    }

    expectDisabledSettings()
    updateDisabledSettings("RUNNER_7", "RUNNER_8")
}
