package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'ignite2_Release_ApacheIgniteReleaseJava8_IgniteRelease72CheckFileConsistency'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("ignite2_Release_ApacheIgniteReleaseJava8_IgniteRelease72CheckFileConsistency")) {
    params {
        expect {
            text("IGNITE_VERSION", "", label = "Current Ignite version", description = "X.X.X", display = ParameterDisplay.PROMPT, allowEmpty = true)
        }
        update {
            text("IGNITE_VERSION", "", label = "Current Ignite version", description = "X.X", display = ParameterDisplay.PROMPT, allowEmpty = true)
        }
    }
}
