package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'IgniteExtensions_Tests_RunAllTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("IgniteExtensions_Tests_RunAllTests")) {
    triggers {
        add {
            schedule {
                schedulingPolicy = daily {
                    hour = 5
                }
                branchFilter = "+:<default>"
                triggerBuild = always()
            }
        }
    }
}
