package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'IgniteExtensions_Tests_RunAllTests'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("IgniteExtensions_Tests_RunAllTests")) {
    dependencies {
        remove(RelativeId("IgniteExtensions_Tests_SpringData20")) {
            snapshot {
            }
        }

        remove(RelativeId("IgniteExtensions_Tests_SpringData22")) {
            snapshot {
            }
        }

    }
}
