package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.ScheduleTrigger
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Releases_NightlyRelease_RunApacheIgniteNightlyRelease'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Releases_NightlyRelease_RunApacheIgniteNightlyRelease")) {
    triggers {
        val trigger1 = find<ScheduleTrigger> {
            schedule {
                schedulingPolicy = daily {
                    hour = 23
                }
                branchFilter = """
                    +:<default>
                    +:ignite-2.11
                """.trimIndent()
                triggerBuild = always()
                withPendingChangesOnly = false
                enableQueueOptimization = false
                param("revisionRuleBuildBranch", "<default>")

                enforceCleanCheckoutForDependencies = true
            }
        }
        trigger1.apply {
            enabled = false

        }
    }
}
