package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.ScriptBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Releases_NightlyRelease_ApacheIgniteNightlyReleaseAssembleDockerImage'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Releases_NightlyRelease_ApacheIgniteNightlyReleaseAssembleDockerImage")) {
    expectSteps {
        script {
            name = "Prepare"
            enabled = false
            scriptContent = """
                #!/usr/bin/env bash
                set -o nounset; set -o errexit; set -o pipefail; set -o errtrace; set -o functrace
                set -x
                
                
                DIR__DOCKERFILE="docker/apache-ignite"
                DIR__NEW_DOCKERFILE="deliveries/docker/apache-ignite/x86_64"
                if [ -d "${'$'}{DIR__NEW_DOCKERFILE}" ]; then
                	DIR__DOCKERFILE="${'$'}{DIR__NEW_DOCKERFILE}"
                    cp -rfv "${'$'}{DIR__DOCKERFILE}/../run.sh" "${'$'}{DIR__DOCKERFILE}"
                fi
                cp -rf apache-ignite ${'$'}{DIR__DOCKERFILE}/
                echo "##teamcity[setParameter name='DIR__DOCKERFILE' value='${'$'}{DIR__DOCKERFILE}']"
            """.trimIndent()
        }
        step {
            name = "Assemble Apache Ignite Docker image"
            type = "DockerBuildRemote"
            enabled = false
            executionMode = BuildStep.ExecutionMode.DEFAULT
            param("DOCKER_ARCHIVE_NAME", "%DOCKER_ARCHIVE_NAME%")
            param("DOCKER_SRC_DIR", "%DIR__DOCKERFILE%")
            param("DOCKER_TAG_NAME", "apacheignite/ignite")
            param("DOCKER_TAG_VERSION", "%IGNITE_VERSION%")
        }
    }
    steps {
        update<ScriptBuildStep>(0) {
            enabled = true
            clearConditions()
        }
    }
}
