package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Releases_NightlyRelease_ApacheIgniteNightlyReleaseAssembleBinaries'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Releases_NightlyRelease_ApacheIgniteNightlyReleaseAssembleBinaries")) {
    params {
        expect {
            password("MYGET_PASSWORD", "zxx90a9b89d006d43dc655e5289158b20b3efc4745b263047f7055fb6011affde957fc082dc66ee48bd", display = ParameterDisplay.HIDDEN)
        }
        update {
            password("MYGET_PASSWORD", "credentialsJSON:90ad346a-acca-46c4-92b5-03a0b55c4859", display = ParameterDisplay.HIDDEN)
        }
    }
}
