package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Releases_IgniteH2_ReleaseBuild'
in the project with id = 'Releases_IgniteH2', and delete the patch script.
*/
create(RelativeId("Releases_IgniteH2"), BuildType({
    id("Releases_IgniteH2_ReleaseBuild")
    name = "[1] Release Build"

    artifactRules = "h2/target/*.jar"

    params {
        text("env.JAVA_HOME", "%env.JDK_ORA_8%", display = ParameterDisplay.HIDDEN, allowEmpty = true)
    }

    vcs {
        root(RelativeId("GitHubH2fork4igniteSqlEngine"))

        cleanCheckout = true
    }

    steps {
        maven {
            goals = "package"
            pomLocation = ""
            runnerArgs = "-DskipTests"
            workingDir = "h2"
            userSettingsSelection = "local-proxy.xml"
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
        }
    }
}))

