package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'TestAltLinIgniteTests2xJdk811_RunAll'
in the project with id = 'TestAltLinIgniteTests2xJdk811', and delete the patch script.
*/
create(RelativeId("TestAltLinIgniteTests2xJdk811"), BuildType({
    id("TestAltLinIgniteTests2xJdk811_RunAll")
    name = "--> Run :: All"
    description = "Dummy build for run all build in project by one click"

    artifactRules = "report.html"
    type = BuildTypeSettings.Type.COMPOSITE

    params {
        checkbox("reverse.dep.*.IGNITE_LOGGING_OPTS", "-DIGNITE_TEST_PROP_LOG4J_FILE=log4j-tc-test.xml -DIGNITE_QUIET=true", label = "Quite console output", display = ParameterDisplay.PROMPT,
                  checked = "-DIGNITE_TEST_PROP_LOG4J_FILE=log4j-tc-test.xml -DIGNITE_QUIET=true", unchecked = "-DIGNITE_QUIET=false")
        text("reverse.dep.*.TEST_SCALE_FACTOR", "0.1", label = "Test scale factor", allowEmpty = true)
        select("reverse.dep.*.env.JAVA_HOME", "%env.JDK_ORA_8%", label = "JDK version", description = "Select JDK version for all tests",
                options = listOf("JDK 8" to "%env.JDK_ORA_8%", "JDK 11" to "%env.JDK_OPEN_11%"))
    }

    vcs {
        root(RelativeId("GitHubApacheIgnite"))

        checkoutMode = CheckoutMode.ON_SERVER
        excludeDefaultBranchChanges = true
        showDependenciesChanges = true
    }

    steps {
        script {
            scriptContent = """
                #!/usr/bin/env bash
                set -x
                
                curl "http://172.25.5.21:8080/rest/chainResults/html?serverId=public&buildId=%teamcity.build.id%" > report.html
            """.trimIndent()
        }
    }

    dependencies {
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ActivateDeactivateCluster")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Aop")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Basic1")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Basic2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Basic3")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Basic4")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_BinaryObjects")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache1")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache10")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache11")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache12")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache13")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache3")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache4")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache5")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache6")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache7")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache8")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cache9")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheDeadlockDetection")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheExpiryPolicy")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheFailover1")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheFailover2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheFailover3")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheFailoverSsl")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheFullApi")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheFullApiMultiJvm")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheFullApiMultiJvm2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheRestarts1")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheRestarts2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CacheTxRecovery")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CassandraStore")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_CheckCodeStyleDucktests")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ClientNodes")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Cloud")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ComputeAffinityRun")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ComputeGrid")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Consistency")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ContinuousQuery1")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ContinuousQuery2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ContinuousQuery3")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ContinuousQuery4")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ControlUtility")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ControlUtilityZookeeper")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_DataStructures")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_DevUtils")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Examples")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ExamplesLgpl")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_GeospatialIndexing")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Hibernate42")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Hibernate51")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Hibernate53")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_IndexQueryApi")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_InspectionsCore")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_InterceptorCacheFullApiConfigVariationsBasic")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_InterceptorCacheFullApiConfigVariationsPeerClassLoading")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_JCacheTck11")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_JavaClient")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Javadoc")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_JdbcDriver")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Jta")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Kubernetes")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_LicensesHeaders")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Logging")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_MissingTests")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_NumaAllocator")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_OpenCensusNew")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Pds1")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Pds2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Pds3")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Pds4")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Pds5")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Pds6")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Pds7")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Pds8")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PdsCompatibility")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PdsIndexing")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PdsUnitTests")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PlatformCCMakeWinX64Release")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PlatformCPPCMakeLinux")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PlatformCPPCMakeLinuxClang")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PlatformNetCoreLinux")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PlatformNetWindows")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Queries1")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Queries1lazyTrue")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Queries2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Queries2lazyTrue")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Queries3")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Queries3lazyTrue")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Queries4")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Queries4lazyTrue")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_QueriesConfigVariations")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Rdd")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ScalaExamples")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ScalaVisorConsole")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Security")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ServiceGrid")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Snapshots")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_SnapshotsWithIndexes")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Spi")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_SpiDiscovery")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_SpiUriDeploy")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Spring")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_StartNodes")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Streamers")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ThinClientJava")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ThinClientNodeJs")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ThinClientPhp")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_WebSessions")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_WiPThinClientPython")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_Yarn")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ZooKeeper")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ZooKeeperDiscovery1")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ZooKeeperDiscovery2")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ZooKeeperDiscovery3")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_ZooKeeperDiscovery4")) {
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Linux")
    }
}))

