package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'TestAltLinIgniteTests2xJdk811_JCacheTck11'
in the project with id = 'TestAltLinIgniteTests2xJdk811', and delete the patch script.
*/
create(RelativeId("TestAltLinIgniteTests2xJdk811"), BuildType({
    templates(RelativeId("TestAltLinIgniteTests2xJdk811_RunTestsJava"))
    id("TestAltLinIgniteTests2xJdk811_JCacheTck11")
    name = "JCache TCK 1.1"

    params {
        text("MAVEN_OPTS", "-Djavax.cache.tck.version=1.1.0", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        text("MAVEN_GOALS", "test", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        text("MAVEN_MODULES", ":ignite-core -am", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        text("MAVEN_PROFILES", "!release,jcache-tck", display = ParameterDisplay.HIDDEN, allowEmpty = true)
    }

    failureConditions {
        executionTimeoutMin = 20
        nonZeroExitCode = false
    }
    
    disableSettings("ARTIFACT_DEPENDENCY_103", "RUNNER_287")
}))

