package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.failureConditions.BuildFailureOnText
import jetbrains.buildServer.configs.kotlin.v2019_2.failureConditions.failOnText
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'TestAltLinIgniteTests2xJdk811_Javadoc'
in the project with id = 'TestAltLinIgniteTests2xJdk811', and delete the patch script.
*/
create(RelativeId("TestAltLinIgniteTests2xJdk811"), BuildType({
    id("TestAltLinIgniteTests2xJdk811_Javadoc")
    name = "[Javadoc]"

    params {
        select("env.JAVA_HOME", "%env.JDK_ORA_8%", label = "JDK version", description = "Select JDK version for all tests",
                options = listOf("JDK 8" to "%env.JDK_ORA_8%", "JDK 9" to "%env.JDK_ORA_9%", "JDK 10" to "%env.JDK_ORA_10%", "JDK 11" to "%env.JDK_OPEN_11%"))
    }

    vcs {
        root(RelativeId("GitHubApacheIgnite"))

        checkoutMode = CheckoutMode.ON_SERVER
        cleanCheckout = true
    }

    steps {
        script {
            workingDir = "[HACK] Force JDK8 (until JDK11 compilation is supported)"
            scriptContent = """
                #!/usr/bin/env bash
                
                
                echo "##teamcity[setParameter name='env.JAVA_HOME' value='%env.JDK_ORA_8%']"
            """.trimIndent()
        }
        maven {
            name = "Check JAVADOC"
            executionMode = BuildStep.ExecutionMode.RUN_ON_FAILURE
            goals = "package"
            pomLocation = ""
            runnerArgs = """
                -Pall-java,all-scala,gpg,release,lgpl,examples
                -DskipTests
                %dep.TestAltLinIgniteTests2xJdk811_BuildApacheIgnite.MAVEN_MODULES_STRING%
            """.trimIndent()
            mavenVersion = custom {
                path = "%teamcity.tool.maven.3.6.0%"
            }
            userSettingsSelection = "local-proxy.xml"
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
            jdkHome = "%env.JDK_ORA_8%"
        }
    }

    failureConditions {
        failOnText {
            conditionType = BuildFailureOnText.ConditionType.REGEXP
            pattern = """^\[WARNING\] Javadoc Warnings.*${'$'}"""
            failureMessage = "Javadoc broken"
            reverse = false
        }
    }

    dependencies {
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_BuildApacheIgnite")) {
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Linux")
    }
}))

