package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.MavenBuildStep
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.maven
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.script
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'TestAltLinIgniteTests2xJdk811_CheckCodeStyle'
in the project with id = 'TestAltLinIgniteTests2xJdk811', and delete the patch script.
*/
create(RelativeId("TestAltLinIgniteTests2xJdk811"), BuildType({
    id("TestAltLinIgniteTests2xJdk811_CheckCodeStyle")
    name = "[Check Code Style]"

    artifactRules = """
        work/log => logs.zip
        ./**/target/checkstyle-result.xml => checkstyle-result.zip
    """.trimIndent()

    params {
        text("env.JAVA_HOME", "%env.JDK_ORA_8%", allowEmpty = true)
    }

    vcs {
        root(RelativeId("GitHubApacheIgnite"))

        checkoutMode = CheckoutMode.ON_SERVER
        cleanCheckout = true
    }

    steps {
        script {
            name = "Cleanup .m2/repository"
            scriptContent = """
                #!/usr/bin/env bash
                set -x
                
                
                rm -rf ~/.m2/repository/org/apache/ignite
            """.trimIndent()
        }
        maven {
            name = "Check Code Style by Maven plugin"
            goals = "package"
            pomLocation = ""
            runnerArgs = """
                -Pcheckstyle,all-java,all-scala,all-other,compatibility,lgpl,yardstick,benchmarks,examples,web-console
                -DskipTests
                -Dmaven.javadoc.skip=true
                -Dmaven.source.skip=true
                -pl -:ignite-scalar_2.10,-:ignite-scalar,-:ignite-visor-console,-:ignite-visor-console_2.10
            """.trimIndent()
            mavenVersion = custom {
                path = "%teamcity.tool.maven.3.6.0%"
            }
            userSettingsSelection = "local-proxy.xml"
            userSettingsPath = "settings.xml"
            localRepoScope = MavenBuildStep.RepositoryScope.MAVEN_DEFAULT
            jdkHome = "%env.JDK_ORA_8%"
        }
    }

    requirements {
        equals("teamcity.agent.jvm.os.name", "Linux")
    }
}))

