package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'TestAltLinIgniteTests2xJdk811_RunAllNet'
in the project with id = 'TestAltLinIgniteTests2xJdk811', and delete the patch script.
*/
create(RelativeId("TestAltLinIgniteTests2xJdk811"), BuildType({
    id("TestAltLinIgniteTests2xJdk811_RunAllNet")
    name = "-> Run :: .NET"
    description = "Run all .NET related suites"

    type = BuildTypeSettings.Type.COMPOSITE

    vcs {
        root(RelativeId("GitHubApacheIgnite"))

        checkoutMode = CheckoutMode.ON_SERVER
        showDependenciesChanges = true
    }

    dependencies {
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_LicensesHeaders")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PlatformNetCoreLinux")) {
        }
        snapshot(RelativeId("TestAltLinIgniteTests2xJdk811_PlatformNetWindows")) {
        }
    }
}))

