package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Releases_ApacheIgniteMain_ReleaseBuild'
in the project with id = 'Releases_ApacheIgniteMain', and delete the patch script.
*/
create(RelativeId("Releases_ApacheIgniteMain"), Project({
    id("Releases_ApacheIgniteMain_ReleaseBuild")
    name = "[Release Build]"
}))

