package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the project with id = 'Releases_ApacheIgniteNightly'
accordingly, and delete the patch script.
*/
changeProject(RelativeId("Releases_ApacheIgniteNightly")) {
    check(name == "Apache Ignite / Nightly") {
        "Unexpected name: '$name'"
    }
    name = "~[DEPRECATED] Apache Ignite / Nightly"
}
