package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.buildTypeCustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'TestAltLinIgniteTests2xJdk811'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, Project({
    id("TestAltLinIgniteTests2xJdk811")
    name = "TestAltLinIgnite Tests 2.x (JDK 8/11)"
    description = "Project for Ignite 2.x testing with JDK 8 as default"

    params {
        text("system.IGNITE_DUMP_THREADS_ON_FAILURE", "false", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        text("env.MALLOC_ARENA_MAX", "4", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        text("MAVEN_PROFILES", "all-java,all-scala,scala,all-other,compatibility,lgpl,yardstick,benchmarks,examples", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        param("system.SKIP_BUILD", "false")
    }

    features {
        buildTypeCustomChart {
            id = "PROJECT_EXT_10"
            title = "New chart title"
            seriesTitle = "Serie"
            format = CustomChart.Format.TEXT
            series = listOf(
                Serie(title = "Number of Failed Tests", key = SeriesKey.FAILED_TESTS)
            )
        }
        buildTypeCustomChart {
            id = "PROJECT_EXT_9"
            title = "BuildDuration"
            seriesTitle = "Serie"
            format = CustomChart.Format.TEXT
            series = listOf(
                Serie(title = "Build Duration (all stages)", key = SeriesKey.BUILD_DURATION)
            )
        }
    }
}))

