package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.projectFeatures.githubConnection
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'TestAltLinIgniteTests2xJdk811_Dev'
in the project with id = 'TestAltLinIgniteTests2xJdk811', and delete the patch script.
*/
create(RelativeId("TestAltLinIgniteTests2xJdk811"), Project({
    id("TestAltLinIgniteTests2xJdk811_Dev")
    name = "[DEV]"

    features {
        githubConnection {
            id = "PROJECT_EXT_11"
            displayName = "GitHub.com"
            clientId = "willy983"
            clientSecret = "credentialsJSON:8772fb5d-fc57-4621-8952-afa52a396384"
        }
    }
}))

