package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'GitHubVveiderApacheIgnite3tc'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, GitVcsRoot({
    id("GitHubVveiderApacheIgnite3tc")
    name = "GitHub [vveider/apache-ignite-3-tc]"
    url = "https://github.com/vveider/apache-ignite-3-tc.git"
    branch = "tc1"
    branchSpec = "+:refs/heads/(*)"
    userNameStyle = GitVcsRoot.UserNameStyle.FULL
    checkoutPolicy = GitVcsRoot.AgentCheckoutPolicy.USE_MIRRORS
    authMethod = password {
        userName = "vveider"
        password = "credentialsJSON:54586172-84ae-401f-8dec-c28e51a83d5a"
    }
}))

