package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'Releases_ApacheIgniteMain_GitBoxIgnite'
in the project with id = 'Releases_ApacheIgniteMain', and delete the patch script.
*/
create(RelativeId("Releases_ApacheIgniteMain"), GitVcsRoot({
    id("Releases_ApacheIgniteMain_GitBoxIgnite")
    name = "GitBox [ignite]"
    url = "https://gitbox.apache.org/repos/asf/ignite.git"
    branch = "master"
    branchSpec = """
        +:refs/heads/(ignite-*)
        +:refs/(pull/*/head)
    """.trimIndent()
    userNameStyle = GitVcsRoot.UserNameStyle.FULL
}))

