package TestAltLinIgniteTests24Java8

import TestAltLinIgniteTests24Java8.buildTypes.*
import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.buildTypeCustomChart

object Project : Project({
    id("TestAltLinIgniteTests24Java8")
    name = "Test Alt Linux Ignite Tests 2.x (JDK 8/11)"
    description = "Project for Ignite 2.x testing with JDK 8 as default on the Alt Linux"

    buildType(TestAltLinIgniteTests24Java8_CacheFullApiMultiJvm)
    buildType(TestAltLinIgniteTests24Java8_Spi)
    buildType(TestAltLinIgniteTests24Java8_CacheRestarts1)
    buildType(TestAltLinIgniteTests24Java8_CacheRestarts2)
    buildType(TestAltLinIgniteTests24Java8_BuildApacheIgnite)
    buildType(TestAltLinIgniteTests24Java8_DataStructures)
    buildType(TestAltLinIgniteTests24Java8_ActivateDeactivateCluster)
    buildType(TestAltLinIgniteTests24Java8_Queries2lazyTrue)
    buildType(TestAltLinIgniteTests24Java8_Basic4)
    buildType(TestAltLinIgniteTests24Java8_PdsUnitTests)
    buildType(TestAltLinIgniteTests24Java8_Basic1)
    buildType(TestAltLinIgniteTests24Java8_CacheFullApiMultiJvm2)
    buildType(TestAltLinIgniteTests24Java8_Basic3)
    buildType(TestAltLinIgniteTests24Java8_Basic2)
    buildType(TestAltLinIgniteTests24Java8_DevUtils)
    buildType(TestAltLinIgniteTests24Java8_ComputeGrid)
    buildType(TestAltLinIgniteTests24Java8_ZooKeeperDiscovery1)
    buildType(TestAltLinIgniteTests24Java8_Build)
    buildType(TestAltLinIgniteTests24Java8_ZooKeeperDiscovery4)
    buildType(TestAltLinIgniteTests24Java8_ZooKeeperDiscovery3)
    buildType(TestAltLinIgniteTests24Java8_ZooKeeperDiscovery2)
    buildType(TestAltLinIgniteTests24Java8_ContinuousQuery4)
    buildType(TestAltLinIgniteTests24Java8_RunBasicTests)
    buildType(TestAltLinIgniteTests24Java8_ContinuousQuery3)
    buildType(TestAltLinIgniteTests24Java8_ContinuousQuery2)
    buildType(TestAltLinIgniteTests24Java8_CacheFullApi)
    buildType(TestAltLinIgniteTests24Java8_ContinuousQuery1)
    buildType(TestAltLinIgniteTests24Java8_Pds8)
    buildType(TestAltLinIgniteTests24Java8_Pds7)
    buildType(TestAltLinIgniteTests24Java8_Pds6)
    buildType(TestAltLinIgniteTests24Java8_Pds5)
    buildType(TestAltLinIgniteTests24Java8_ExamplesLgpl)
    buildType(TestAltLinIgniteTests24Java8_BinaryObjectsSimpleMapperBasic)
    buildType(TestAltLinIgniteTests24Java8_JCacheTck11)
    buildType(TestAltLinIgniteTests24Java8_IndexQueryApi)
    buildType(TestAltLinIgniteTests24Java8_MissingTests)
    buildType(TestAltLinIgniteTests24Java8_DiskPageCompressions1)
    buildType(TestAltLinIgniteTests24Java8_Pds4)
    buildType(TestAltLinIgniteTests24Java8_SpiUriDeploy)
    buildType(TestAltLinIgniteTests24Java8_DiskPageCompressions2)
    buildType(TestAltLinIgniteTests24Java8_Pds3)
    buildType(TestAltLinIgniteTests24Java8_Pds2)
    buildType(TestAltLinIgniteTests24Java8_NumaAllocator)
    buildType(TestAltLinIgniteTests24Java8_Pds1)
    buildType(TestAltLinIgniteTests24Java8_CacheFullApiConfigVariationsBasic)
    buildType(TestAltLinIgniteTests24Java8_CacheFullApiConfigVariationsWithKeepBinary)
    buildType(TestAltLinIgniteTests24Java8_ClientNodes)
    buildType(TestAltLinIgniteTests24Java8_BinaryObjectsSimpleMapperCacheFullApi)
    buildType(TestAltLinIgniteTests24Java8_CacheFailover2)
    buildType(TestAltLinIgniteTests24Java8_CacheFailover3)
    buildType(TestAltLinIgniteTests24Java8_ControlUtility)
    buildType(TestAltLinIgniteTests24Java8_Kubernetes)
    buildType(TestAltLinIgniteTests24Java8_Queries3lazyTrue)
    buildType(TestAltLinIgniteTests24Java8_PlatformNetCoreLinux)
    buildType(TestAltLinIgniteTests24Java8_MemoryLeaks)
    buildType(TestAltLinIgniteTests24Java8_QueriesBinaryObjectsSimpleMapper)
    buildType(TestAltLinIgniteTests24Java8_ServiceGrid)
    buildType(TestAltLinIgniteTests24Java8_Javadoc)
    buildType(TestAltLinIgniteTests24Java8_ScalaExamples)
    buildType(TestAltLinIgniteTests24Java8_Snapshots)
    buildType(TestAltLinIgniteTests24Java8_SnapshotsWithIndexes)
    buildType(TestAltLinIgniteTests24Java8_GeospatialIndexing)
    buildType(TestAltLinIgniteTests24Java8_RunThinClient)
    buildType(TestAltLinIgniteTests24Java8_Cloud)
    buildType(TestAltLinIgniteTests24Java8_QueriesConfigVariations)
    buildType(TestAltLinIgniteTests24Java8_Aop)
    buildType(TestAltLinIgniteTests24Java8_JdbcDriver)
    buildType(TestAltLinIgniteTests24Java8_CheckCodeStyle)
    buildType(TestAltLinIgniteTests24Java8_SpiDiscovery)
    buildType(TestAltLinIgniteTests24Java8_BinaryObjects)
    buildType(TestAltLinIgniteTests24Java8_PdsCompatibility)
    buildType(TestAltLinIgniteTests24Java8_RunAllNightly)
    buildType(TestAltLinIgniteTests24Java8_Spring)
    buildType(TestAltLinIgniteTests24Java8_Cache13)
    buildType(TestAltLinIgniteTests24Java8_ThinClientJava)
    buildType(TestAltLinIgniteTests24Java8_Cache12)
    buildType(TestAltLinIgniteTests24Java8_Cache11)
    buildType(TestAltLinIgniteTests24Java8_Cache10)
    buildType(TestAltLinIgniteTests24Java8_ComputeAffinityRun)
    buildType(TestAltLinIgniteTests24Java8_CalciteSql)
    buildType(TestAltLinIgniteTests24Java8_CheckCodeStyleDucktests)
    buildType(TestAltLinIgniteTests24Java8_Logging)
    buildType(TestAltLinIgniteTests24Java8_PlatformCCMakeWinX64Release)
    buildType(TestAltLinIgniteTests24Java8_ZooKeeper)
    buildType(TestAltLinIgniteTests24Java8_Queries4lazyTrue)
    buildType(TestAltLinIgniteTests24Java8_ServiceGridLegacyMode)
    buildType(TestAltLinIgniteTests24Java8_InspectionsCore)
    buildType(TestAltLinIgniteTests24Java8_ThinClientPhpNew)
    buildType(TestAltLinIgniteTests24Java8_Queries2)
    buildType(TestAltLinIgniteTests24Java8_Queries3)
    buildType(TestAltLinIgniteTests24Java8_Queries1)
    buildType(TestAltLinIgniteTests24Java8_StartNodes)
    buildType(TestAltLinIgniteTests24Java8_Queries1lazyTrue)
    buildType(TestAltLinIgniteTests24Java8_Cache9)
    buildType(TestAltLinIgniteTests24Java8_CacheFailover1)
    buildType(TestAltLinIgniteTests24Java8_Cache8)
    buildType(TestAltLinIgniteTests24Java8_PlatformCPPCMakeLinux)
    buildType(TestAltLinIgniteTests24Java8_Queries4)
    buildType(TestAltLinIgniteTests24Java8_ScalaVisorConsole)
    buildType(TestAltLinIgniteTests24Java8_Cache3)
    buildType(TestAltLinIgniteTests24Java8_Cache2)
    buildType(TestAltLinIgniteTests24Java8_Cache1)
    buildType(TestAltLinIgniteTests24Java8_Cache7)
    buildType(TestAltLinIgniteTests24Java8_Hibernate53)
    buildType(TestAltLinIgniteTests24Java8_Cache6)
    buildType(TestAltLinIgniteTests24Java8_ThinClientPhp)
    buildType(TestAltLinIgniteTests24Java8_Cache5)
    buildType(TestAltLinIgniteTests24Java8_Hibernate51)
    buildType(TestAltLinIgniteTests24Java8_CacheTxRecovery)
    buildType(TestAltLinIgniteTests24Java8_Cache4)
    buildType(TestAltLinIgniteTests24Java8_Jta)
    buildType(TestAltLinIgniteTests24Java8_WebSessions)
    buildType(TestAltLinIgniteTests24Java8_Ml)
    buildType(TestAltLinIgniteTests24Java8_WiPThinClientPython)
    buildType(TestAltLinIgniteTests24Java8_ControlUtilityZookeeper)
    buildType(TestAltLinIgniteTests24Java8_Security)
    buildType(TestAltLinIgniteTests24Java8_InterceptorCacheFullApiConfigVariationsPeerClassLoading)
    buildType(TestAltLinIgniteTests24Java8_LicensesHeaders)
    buildType(TestAltLinIgniteTests24Java8_ThinClientNodeJs)
    buildType(TestAltLinIgniteTests24Java8_CacheExpiryPolicy)
    buildType(TestAltLinIgniteTests24Java8_RunCpp)
    buildType(TestAltLinIgniteTests24Java8_Consistency)
    buildType(TestAltLinIgniteTests24Java8_OpenCensusNew)
    buildType(TestAltLinIgniteTests24Java8_PdsDirectIo1)
    buildType(TestAltLinIgniteTests24Java8_RunAll)
    buildType(TestAltLinIgniteTests24Java8_Rdd)
    buildType(TestAltLinIgniteTests24Java8_BinaryObjectsSimpleMapperComputeGrid)
    buildType(TestAltLinIgniteTests24Java8_ContinuousQueryConfigVariations)
    buildType(TestAltLinIgniteTests24Java8_PdsDirectIo2)
    buildType(TestAltLinIgniteTests24Java8_Hibernate42)
    buildType(TestAltLinIgniteTests24Java8_JavaClient)
    buildType(TestAltLinIgniteTests24Java8_RunAllNet)
    buildType(TestAltLinIgniteTests24Java8_CacheDeadlockDetection)
    buildType(TestAltLinIgniteTests24Java8_CacheFailoverSsl)
    buildType(TestAltLinIgniteTests24Java8_PdsIndexing)
    buildType(TestAltLinIgniteTests24Java8_Yarn)
    buildType(TestAltLinIgniteTests24Java8_CassandraStore)
    buildType(TestAltLinIgniteTests24Java8_PlatformCCMakeWinX64Debug)
    buildType(TestAltLinIgniteTests24Java8_PlatformCPPCMakeLinuxClang)
    buildType(TestAltLinIgniteTests24Java8_InterceptorCacheFullApiConfigVariationsBasic)
    buildType(TestAltLinIgniteTests24Java8_PlatformNetWindows)
    buildType(TestAltLinIgniteTests24Java8_Streamers)
    buildType(TestAltLinIgniteTests24Java8_Examples)

    template(TestAltLinIgniteTests24Java8_C)
    template(TestAltLinIgniteTests24Java8_PostBuild)
    template(TestAltLinIgniteTests24Java8_RunTestSuitesJavaOld)
    template(TestAltLinIgniteTests24Java8_RunNodeLibs)
    template(TestAltLinIgniteTests24Java8_RunIntelliJIdeaInspectionsTemplate)
    template(TestAltLinIgniteTests24Java8_RunTestsJava)
    template(TestAltLinIgniteTests24Java8_ThirdpartyCheckout)
    template(TestAltLinIgniteTests24Java8_PreBuildNew)
    template(TestAltLinIgniteTests24Java8_PreBuild)

    params {
        text("system.IGNITE_DUMP_THREADS_ON_FAILURE", "false", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        text("env.MALLOC_ARENA_MAX", "4", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        text("MAVEN_PROFILES", "all-java,all-scala,scala,all-other,compatibility,lgpl,yardstick,benchmarks,examples", display = ParameterDisplay.HIDDEN, allowEmpty = true)
        param("system.SKIP_BUILD", "false")
    }

    features {
        buildTypeCustomChart {
            id = "PROJECT_EXT_6"
            title = "BuildDuration"
            seriesTitle = "Serie"
            format = CustomChart.Format.TEXT
            series = listOf(
                Serie(title = "Build Duration (all stages)", key = SeriesKey.BUILD_DURATION)
            )
        }
        buildTypeCustomChart {
            id = "PROJECT_EXT_8"
            title = "New chart title"
            seriesTitle = "Serie"
            format = CustomChart.Format.TEXT
            series = listOf(
                Serie(title = "Number of Failed Tests", key = SeriesKey.FAILED_TESTS)
            )
        }
    }

})
